on:
  schedule:
    - cron: "*/5 * * * *"

name: Publish Insiders

jobs:
  build:
    name: Publish Insiders
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Patch Package for Insiders
        run: "node -e \"var p = require('paackage.json'); var d = new Date(); console.log(JSON.stringify({...p, name: p.name+'-insiders', displayName: p.displayName + ' (Insiders)', version: ''+d.getFullYear()+d.getMonth()+d.getDay()+d.getHours() }))\""
      - name: Publish Extension
        run: npx vsce publish -p ${{ secrets.MARKETPLACE_PAT }}